### ISSUE TITLE
Continuous, rather than discrete zooming

### ISSUE THREAD

**Issue by iangilman** [DDMAL/diva.js#115]
The standard these days is continuous zooming, such as with Google Maps. Perhaps some technology like OpenSeadragon:

http://thatcher.github.com/openseadragon/

… mixed with your document handling technology might be interesting.

**Comment by ahankinson** [comment]
It's still on our radar, but just not for this release.

**Comment by iangilman** [comment]
Right on. OpenSeadragon has come a long way since then: 

http://openseadragon.github.io/

**Comment by jeromepl** [comment]
Will be fixed in Diva 5.0
