### ISSUE TITLE
Overlays?

### ISSUE THREAD

**Issue by rsimon** [DDMAL/diva.js#116]
This is really a question rather than an issue - hope you don't mind me posting this here!

I'm sounding out the possibility to integrate annotation functionality into diva.js. I'm running a small JS annotation library here on github (github.com/annotorious) and would like to extend it to support zoomable images/a document viewer.

Is there a maybe a way already to add simple (box) overlays in diva.js? E.g. anchor a DIV of predefined size/location which then scales/moves along with the image? If so, integration with my annotation library would be quite straightforward. If not, I'd be willing to help out if time permits?

Cheers,
Rainer

**Comment by ahankinson** [comment]
I'm going to close this one since the highlight plugin + IIIF is the way we're going with this.
