### ISSUE TITLE
Integrate other image processing tools into Canvas view

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#131]
We've got a library of some JS Image processing tools (binarization, de-speckling, etc.) (See DDMAL/js-image-suite). Should we add these to the canvas plugin (and make them optional to turn on or off?

Also, we should look at reviving our colour replacement functionality, i.e., pick a pixel colour, choose a replacement colour, and all instances of that colour pixel are replaced by the replacement pixel.

We might consider looking at the [DIAMM Image Restoration Handbook](http://www.diamm.ac.uk/redist/pdf/RestorationWorkbook.pdf) for more ideas of some MSS image enhancement tools.

**Comment by ahankinson** [comment]
This will be punted to a later release.

**Comment by EricHanLiu** [comment]
Largely implemented in the Manipulation plugin in Diva 6
