### ISSUE TITLE
Irregular scrolling: Page div scrolling focus / limit

### ISSUE THREAD

**Issue by magoni** [DDMAL/diva.js#204]
When the mouse is positioned over a `.diva-document-[tile|page]` div and the user is scrolling, once the end of the page has been hit, the browser thinks that the end of the inner div has been hit, and thus stops scrolling the document pane and instead starts scrolling the whole page.

Reproduced with a Magic Trackpad and Chrome on OS X.

Related to #140.

**Comment by magoni** [comment]
I'll look into this and see if anything has changed for the better in the Chromium codebase for 4.1.

**Comment by magoni** [comment]
Updated issue: https://code.google.com/p/chromium/issues/detail?id=527394

**Comment by EricHanLiu** [comment]
No longer relevant
