### ISSUE TITLE
Travis CI off by one pixel error

### ISSUE THREAD

**Issue by magoni** [DDMAL/diva.js#223]
Travis CI's javascript DOM measurements for the `getState()` and `setState()` unit tests are off from local system measurements by 1 pixel. Results should be consistent when using phantomjs in Travis and locally.

**Comment by ahankinson** [comment]
Can this be closed?

**Comment by ahwitz** [comment]
It's still valid and is causing the tests to run differently between anything running a Linux distro and anything running a Mac distro - check some of the more recent commits when resolving the highlight-upgrade branch, and Evan and I were still dealing with it. https://github.com/ariya/phantomjs/issues/12755 has not been responded to yet.

**Comment by ahankinson** [comment]
But it's not our fault, it's upstream, right?

**Comment by ahwitz** [comment]
To the best of our knowledge/debugging, yes, but we've had to make local changes to compensate for it that need to be reverted once it's fixed.

**Comment by ahankinson** [comment]
Ok, well, we'll close this one and cross that particular bridge when we come to it.
