### ISSUE TITLE
Rounding bug garbles images at specific page widths

### ISSUE THREAD

**Issue by seanaery** [DDMAL/diva.js#243]
It appears if these conditions are BOTH true (with 256x256 tiles), we get a garbled page image:
1. integer width of the page at current zoom level is equal to or a multiple of 256
2. the fraction of a pixel left over is less than 0.5

Diva.js tries to render a < 1px wide column for an image tile that doesn't exist, throwing the layout off.

* Any image 2049px wide breaks at both zoom 2 & 3
* Any image 2050px or 2051px wide breaks at zoom 2

![Garbled layout](http://people.duke.edu/~seanaery/digcoll/docviewer/diva-rounding-bug.png)

### Examples
**2049w breaks at zoom 2 & 3**
http://library.duke.edu/digitalcollections/earlymss_emsgk01018/#z=2&n=5&p=1&y=0&x=62&h=700&w=700
http://library.duke.edu/digitalcollections/earlymss_emsgk01025/#z=2&n=5&p=220&y=0&x=65&h=700&w=700

**2050w breaks at zoom 2**
http://library.duke.edu/digitalcollections/earlymss_emsgk01012/#z=2&n=5&p=2&y=0&x=45&h=700&w=700

**Comment by ahankinson** [comment]
@seanaery Could you send me a few of the images that break and we'll have a look at it? You can e-mail me a dropbox link (or similar) if you like.

**Comment by ahankinson** [comment]
(By "images" I mean the original JPEG2000 or TIFF ones that you're serving with IIP)

**Comment by seanaery** [comment]
Sure @ahankinson, just sent some your way. Thanks!

**Comment by ahankinson** [comment]
@seanaery I just pushed a commit that should fix the problem -- it does on our test server (http://dev.simssa.ca/duke/single.html -- I'll take this down once you confirm).

**Comment by seanaery** [comment]
@ahankinson Excellent, thanks! We will regenerate our JSON files using the script additions early this week. I'll let you know.

**Comment by seanaery** [comment]
Hi @ahankinson -- I used the new generate_json.py script from develop branch, but running a diff shows no change in the output .json file from what we previously had. Looks like your example http://dev.simssa.ca/duke/duke.json has rounded up or down the w and h values for each page at each zoom level and that works great. Your latest commit on develop seems to only try to set the c & r properties, so I wonder if there's another part missing from the commit. If I switch those lines 93-101 to the following and run the script, it appears to work:

```
                if w % 256 < 1:
                    w = int(math.floor(w))
                else:
                    w = int(math.ceil(w))

                if h % 256 < 1:
                    h = int(math.floor(h))
                else:
                    h = int(math.ceil(h))
```

**Comment by ahankinson** [comment]
Ah! You're right. I put a `math.ceil` on w/h when I was testing that didn't make it into this commit. I'll fix that right now. Sorry for the inconvenience.

**Comment by ahankinson** [comment]
That should be better.

**Comment by seanaery** [comment]
Awesome -- that fixed everything! Thanks for the quick work. You can see the pages at the links I sent before now working as intended.

Before running the script, I also changed it to round page heights/widths down (```math.floor```) instead of up (```math.ceil```). On a lot of pages we'd been seeing a 1px line at the right and/or bottom of the page that's simply a repeat of the top or left edge of the outer tile (because of default CSS background-image: repeat). I see this also happens with the Diva.js demo UI (see the first page at default zoom, right-most column https://ddmal.github.io/diva.js/try/single.html )

```
                    'h': math.floor(h),
                    'w': math.floor(w)
```
Rounding down seems to fix it and as far as I can tell doesn't have any negative consequences.

**Comment by ahankinson** [comment]
Cool, thanks for testing that. I've rolled that into `generate_json.py` in commit 4c2d4cc5f4e059bb243f5bff026f9640891c97af.
