### ISSUE TITLE
Update public website with 3.1.0 stable release

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#245]
N/T

**Comment by magoni** [comment]
Fixed via https://github.com/DDMAL/diva.js/commit/914bffe45419ecdbde1c0e0f634377fddf379f28 and https://github.com/DDMAL/diva.js/commit/267bcc07fda48d33bfbd54cfc61915f4e72f321a

**Comment by magoni** [comment]
...and https://github.com/DDMAL/diva.js/commit/395467869b33743bb9f2e7551c91145857bbbac0
