### ISSUE TITLE
Standardize getCurrentPageDimensions

### ISSUE THREAD

**Issue by ahwitz** [DDMAL/diva.js#246]
The availability of get(Current)PageDimensionsAt(Current)(Grid | Zoom)Level is inconsistent. Make sure that we have a consistent mix of (current) options for both grid and zoom and for both currents.

**Comment by EricHanLiu** [comment]
Grid dimensions have been moved to `getGridPagesPerRow`. This essentially covers the current page(s), current grid level, and all combinations.

Closing
