### ISSUE TITLE
Diva tries to load every tile you scroll over

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/diva.js#247]
Diva tries to load every image tile, even when you scroll really fast.

One of the loading timeouts must have gotten messed up.

**Comment by ahankinson** [comment]
Do you know when this was introduced?

**Comment by ahwitz** [comment]
tracing it right now

**Comment by ahwitz** [comment]
bug seems to be present in 3.0.0 or whatever version is on the "try it" part of the Github IO page, running git bisect because it's going to take a while otherwise

**Comment by ahwitz** [comment]
found the commit and what's causing the bug, fixing now

**Comment by ahankinson** [comment]
Can I see it?

**Comment by ahwitz** [comment]
https://github.com/DDMAL/diva.js/commit/65d396e8a938fb7d791c93b1b6b6cc8e72e51dba where old 406 becomes new 448

**Comment by ahankinson** [comment]
Nice catch! My bad...

**Comment by ahwitz** [comment]
Manually closing.
