### ISSUE TITLE
panel size doesn't update on toggle to FullScreen

### ISSUE THREAD

**Issue by seanaery** [DDMAL/diva.js#250]
Looks like the updatePanelSize() function is no longer invoked when toggling from regular view to full-screen. (It does still work going the other way). 

This is problematic in two cases:
1) We have a relatively narrow fixed-width viewer, going to grid view, then fullscreen. The fullscreen thumb grid is still confined to the original width, until you resize the window slightly.
2) In regular view, we zoom in, then go to fullscreen. The tiles at the right fail to load when dragging that way; things render correctly only if you resize the window.

**Comment by ahwitz** [comment]
Two relevant issues to this:

#139 was where the code that says "update only if it's leaving fullscreen" was introduced
#235 provided an internal subscriber to the "PanelSizeDidChange" event that calls updatePanelSize manually.

I'll figure out why this was implemented as an "only if leaving fullscreen" and get back to you ASAP, though publishing the above event should help if you need to keep testing in the meantime.

**Comment by seanaery** [comment]
Cool, thanks. `diva.Events.publish('PanelSizeDidChange'); ` indeed works great for a temporary workaround.

**Comment by ahwitz** [comment]
I just pushed a commit to develop that seemed to resolve the issue on my end. Let me know if it works for you.

**Comment by seanaery** [comment]
Thanks @ahwitz -- that did fix the issue.

**Comment by ahwitz** [comment]
Perfect! Hopefully it doesn't create anything more...
