### ISSUE TITLE
Remove jQuery selectors in isHorizontally/VerticallyInViewport

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#251]
These functions get called a lot and could probably benefit from a more efficient lookup mechanism.

**Comment by magoni** [comment]
This is fixed on the `smooth-zooming` branch via https://github.com/DDMAL/diva.js/commit/e56eab2e3d2b2f80d0f21224de2a403c39d8f237. (These functions now take coordinates as arguments instead of pulling the values from the DOM, allowing us to cache the values i.e. in the case of loops.)
