### ISSUE TITLE
Check to see if this if statement is necessary

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#252]
There's a check here:

https://github.com/DDMAL/diva.js/blob/61358803f016bbc8e47d36894f0a2f17665d8b0a/source/js/diva.js#L290

That looks for `isPageLoaded(pageIndex)`. Then here:

https://github.com/DDMAL/diva.js/blob/61358803f016bbc8e47d36894f0a2f17665d8b0a/source/js/diva.js#L303

We check this again. I'm not sure that this second `if` statement is necessary, since we would never reach it if it passed the first.

**Comment by magoni** [comment]
If `isPageLoaded` evaluates to `false`:
1. the first `if` fails
2. the second `if` passes

So the second `if` is unnecessary in this case.

However, where `isPageLoaded` is true and `allTilesLoaded` is false:
1. the first `if` fails
2. the second `if` fails

In this case, without the second check, we reach the block inside of it. So it's necessary AFAICT.

Related: I think we could save on performance and increase readability by defining `pageLoadFunction` outside of `loadPage`, thus not redefining it every time we call `loadPage`. (And maybe we could rename `pageLoadFunction` to something like `loadTiles`.)
