### ISSUE TITLE
Find a way to make "height" in the LESS spec for .diva-outer more adaptable

### ISSUE THREAD

**Issue by ahwitz** [DDMAL/diva.js#253]
This has caused a bunch of issues (for me) with trying to place a diva-wrapper on the page - if we could set diva-outer to automatically fill its parent and have the user size diva-wrapper as they wish, it might be better.

I don't know if this even needs to be fixed, but I feel weird about having a static size for the element hardcoded in the CSS.

**Comment by wabain** [comment]
I'm leaning towards this being a documentation fix. It's pretty easy to override the height if you just want a value other than 700px. Making Diva fill the wrapper by default would force the user to do more configuration out of the box.

**Comment by jeromepl** [comment]
I will look into doing this using Flex box layout
