### ISSUE TITLE
The image processing script creates JPEG2000 images with the extension .jpeg

### ISSUE THREAD

**Issue by wabain** [DDMAL/diva.js#255]
[Here.](https://github.com/DDMAL/diva.js/blob/a7ed1d4a541334562c19336c422fbf18518be5b5/build/processing/process.py#L125)

The JSON generator correctly expects .jpx or .jp2 files, so it won't process the output of the previous step.

**Comment by magoni** [comment]
Thanks! Let me know if this fix causes any problems—I don't have Kakadu compiled locally so I haven't tested.

**Comment by wabain** [comment]
From a quick test that looks like it fixes it. Thanks!
