### ISSUE TITLE
Wrap up 3.2 release

### ISSUE THREAD

**Issue by ahwitz** [DDMAL/diva.js#259]
-https://github.com/DDMAL/diva.js/commit/0dc52467a5995f09286a387c5bf4db8f3a19d979#commitcomment-11260529 for @magoni

**Comment by magoni** [comment]
Should I package up a release?

**Comment by ahwitz** [comment]
I'll take care of it tonight/tomorrow CEST as I may throw in a few more commits before the buzzer.

**Comment by magoni** [comment]
CEST bon.

**Comment by ahankinson** [comment]
#timezonejokes

**Comment by ahwitz** [comment]
# timezonejokes

**Comment by magoni** [comment]
:cry:

**Comment by AFFogarty** [comment]
:sunny: :airplane: :moon: :airplane: :sunny: :it:

**Comment by fujinaga** [comment]
Congratulations!

Ich
