### ISSUE TITLE
The UpdatePanelSize event should update what pages are displayed

### ISSUE THREAD

**Issue by wabain** [DDMAL/diva.js#260]
The UpdatePanelSize event is supposed to prompt Diva to update its geometry when the panel size is changed by external code; see #235. But currently the event is [only subscribed to](https://github.com/DDMAL/diva.js/blob/9b78df65805e7e7f8a8ae9d68bf30260643e0486/source/js/diva.js#L1922) if one of `enableSpaceScroll` or `enableKeyScroll` is true.

In addition, when the event is triggered, it doesn't recalculate which pages should currently be displayed. If a new page falls within the viewport because of the panel size change, it only appears after something like a scroll event.

(@ahwitz, what we looked at earlier only worked because it happened to be invoked in a place before before Diva's `updatePanelSize` function is called.)

Refs DDMAL/cantus#105

**Comment by ahwitz** [comment]
:+2:

**Comment by magoni** [comment]
Both issues are fixed on `develop`.
