### ISSUE TITLE
Update tools

### ISSUE THREAD

**Issue by magoni** [DDMAL/diva.js#263]
Migrate Diva to Gulp for build tasks (which will give us jshint, watch, and a built-in dev server, among others) and npm for dependency management. Maybe SCSS?

**Comment by fujinaga** [comment]
Have you seen this?
http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt/ <http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt/>

Ich

**Comment by ahankinson** [comment]
I saw that blog and tried doing it all with npm. In the end I gave up and went with gulp. 

1) You're not actually removing any dependencies. If you need to install sass or a file watcher you still need to `npm install -g` them manually.
2) Gulp is nice for piping things through lots of other tools. I quickly lost track of writing out 'temporary' files from some tools and then piping them into other tools (b/c they didn't conform to UNIX stdout pipes or something)
