### ISSUE TITLE
Expose hooks for go to page functions in settings

### ISSUE THREAD

**Issue by wabain** [DDMAL/diva.js#265]
Right now the "go to page" input in the toolbar accepts a number as input and jumps to the page with index `pageNumber - 1`. It would be nice for there to be an option for the user to supply a custom function to do the page lookup, which would be useful to complement the page alias plugin. Ideally this function would take the user's text and input and return a page index, or `null` for an invalid value.

It would also be nice to be able to customize the behavior when a page is invalid. Right now Diva just gives an alert.

Note that this isn't a priority for Cantus Ultimus; I just removed Diva's binding from the submit event.

**Comment by ahwitz** [comment]
@wabain: I know you were thinking about this a while ago, but if you remember: is this the same thing as https://github.com/DDMAL/diva.js/blob/develop/source/js/plugins/pagealias.js#L112, or were you thinking of something different?

**Comment by wabain** [comment]
If I'm remembering how that API works correctly the use case I had in mind is more involved, where you want to handle inputs that don't exactly match the alias of the page. For instance, on for Salzinnes on Cantus Ultimus any of "a1", "a1r", "A1", "A001r", etc. will take you to the folio with the alias A01r. Rather than trying to define general normalization rules, I was thinking that the best way to handle it would be to let the user define whatever function they wanted to handle the mapping.

**Comment by ahwitz** [comment]
Something like https://github.com/DDMAL/diva.js/blob/develop/source/js/plugins/pagealias.js#L18 ?

**Comment by wabain** [comment]
Kind of like the opposite of `pageAliasFunction`, but more general. That takes the page index and returns an alias (or `false`). This takes an arbitrary string entered in the go to page input and returns a page index (in whatever precise output format makes the most sense). If the input string corresponds to the alias of a page then the function should be returning the page index, but it also allows Diva to handle other input values.

**Comment by wabain** [comment]
For reference, the kind of function I had in mind is what i implemented in Cantus Ultimus [here](https://github.com/DDMAL/cantus/blob/c12d2729f40642f2100d24a0146497737b08b341/public/cantusdata/frontend/public/js/app/views/DivaView.js#L251).

**Comment by ahwitz** [comment]
Got it. Was stuck thinking the other way.
