### ISSUE TITLE
Upgrade jQuery

### ISSUE THREAD

**Issue by magoni** [DDMAL/diva.js#268]
We're currently on jQuery 1.8. The current 1.11 (or 2.x if we don't need to support IE < 9) introduces performance improvements, but since we would be upgrading from below 1.9 we need to make sure we're not using any deprecated features (see http://jquery.com/download/).

**Comment by ahankinson** [comment]
I might suggest moving straight to the 2.x branch. It's supposed to be backwards compatible with 1.x for all but IE < 8.0, so it would make sense for us to move.
