### ISSUE TITLE
IIIF Demo does not work on Chrome due to mixed security schemes.

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#271]
Loading the IIIF demo in Chrome gives this error:

"Mixed Content: The page at 'https://ddmal.github.io/diva.js/try/iiif-highlight/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://dev.simssa.ca/iiif/stgallen_390_annotated.json'. This request has been blocked; the content must be served over HTTPS."

For now, can we load the st. gall 390 JSON file on GitHub too?

**Comment by magoni** [comment]
Whoops, will switch the manifest to being stored on Github Pages right away! For some reason, Github doesn't redirect me to the https version of the site. I'm hoping you were able to demo it using the http:// version?

**Comment by ahankinson** [comment]
Yep, it all worked fine!

**Comment by magoni** [comment]
Awesome! I moved our manifest to ddmal.github.io and the demo works on HTTPS now. I am getting warnings that the e-codices images are not served over HTTPS, but they do load in Chrome. Will look into what we can do about image requests over HTTPS once I get back next week.
