### ISSUE TITLE
How can i specify the divID in highlightOnPage()?

### ISSUE THREAD

**Issue by ivanilinov** [DDMAL/diva.js#272]
How can i specify the divID in highlightOnPage() to use in the function gotoHighlight(divID)?
Currently i can only specify divClass: highlightOnPage(pageIdxs, regions, colour, divClass).

**Comment by magoni** [comment]
Hi,

Currently, you have to set the ID of the highlight div manually in your own application after calling `highlightOnPage`. If this doesn't make sense for your use case, we could add an optional div ID argument to `highlightOnPage`.

**Comment by ahwitz** [comment]
The regions array passed in to highlightOnPage takes a "divID" property for each highlight object.

https://github.com/DDMAL/diva.js/blob/master/source/js/plugins/highlight.js#L161

**Comment by magoni** [comment]
Thanks Andrew! Clarifying this point in the documentation.

**Comment by ahwitz** [comment]
Once I get around to fixing and merging all the highlight-upgrade branch changes, I'll revamp the docs on that too. :+1:
