### ISSUE TITLE
Diva assumes it is attached to the document

### ISSUE THREAD

**Issue by wabain** [DDMAL/diva.js#273]
In some places Diva is assuming that the parent element it is called on is attached to the document. Primarily this takes the form of using `document.getElementById` to access sub-elements. This means it breaks in non-obvious ways if the parent element is actually detached from the document. (I stumbled on this while doing some refactoring which had the effect of making Diva initialization happen in a subtree which was assembled before being inserted.)

It would be nice if Diva could do one of the following:

 - Give a warning if `$(elem).diva()` is called when `elem` is not attached to the document, so it's at least clear what went wrong.

 - Use `jQuery.find` or `elem.querySelector` to select sub-elements, so that selection occurs on the proper subtree. (Unfortunately, DOM elements do not have a `getElementById` function.)

 - Cache elements when they are created so that DOM lookup isn't necessary. Most of the usages get the outer element, the inner element, or a page or row by index, so this probably wouldn't be too hard.

 - Do something with DocumentFragment and use `fragment.getElementById` instead of `document.getElementById` where appropriate. Not really sure how this would work.

**Comment by ahankinson** [comment]
Nice! 

A lot of the optimization in Diva has focused on using native JS selectors instead of jQuery, so any solution should try to use the native code if at all possible.

**Comment by ahwitz** [comment]
FWIW, I think document.getElementById("x") == document.querySelectorAll('*[*|id=x]')[0], so a combination of the second and third solutions might be ideal.

**Comment by wabain** [comment]
`document.getElementById("x") === document.querySelector("#x")`, which is even easier. [MDN says](https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelector) this even works with IE, which surprises me.

**Comment by ahwitz** [comment]
:+1:

**Comment by ahankinson** [comment]
Make sure you profile this -- `querySelector` is about 1/3 the speed as `getElementById`

**Comment by wabain** [comment]
This could probably be made to work, and most of the core doesn't rely on element IDs now, but I don't find the use case very compelling anymore. There's no significant performance advantage to instantiating Diva in a document fragment or something and the viewer would need to resize after being attached to the document anyway. If anything, I think Diva should just print an error if it is not attached to the document on instantiation.
