### ISSUE TITLE
Give grid pages and regular pages a single class

### ISSUE THREAD

**Issue by ahwitz** [DDMAL/diva.js#275]
Grid pages are given `.diva-page` while regular pages (non-grid-view) are given `.diva-document-page` only. Is there a reason for this, or can we give both `.diva-page`, grid `.diva-grid-page`, and regular `.diva-document-page`?

Things like https://github.com/DDMAL/diva.js/blob/master/source/js/diva.js#L3014 will apparently not work in grid view, and I didn't even realize that while implementing it.

**Comment by magoni** [comment]
I'll also update `getPageIndexForPageXYValues`...
