### ISSUE TITLE
Document autoscroll plugin and upgrades to the highlight plugin

### ISSUE THREAD

**Issue by ahwitz** [DDMAL/diva.js#276]
Just realized both of these have yet to be done.

**Comment by magoni** [comment]
[Autoscroll plugin](https://github.com/DDMAL/diva.js/wiki/Using-the-Plugins#the-autoscroll-plugin) and [new Highlight plugin functions](https://github.com/DDMAL/diva.js/wiki/The-API-and-Plugins#gotohighlight-divid)
