### ISSUE TITLE
Outdated version in package.json

### ISSUE THREAD

**Issue by wabain** [DDMAL/diva.js#277]
The version in `package.json` on `develop` is still set to v3.1.0 and that's the only version published [on npm](https://www.npmjs.com/package/diva.js). (FYI it's pretty common to have a `release` build taks that takes care of bumping version numbers etc.)

There are also a lot of references to 3.0.0 in the readme. Some of those should maybe be updated as well.

**Comment by ahankinson** [comment]
Sounds to me like you just volunteered to write a task that takes care of bumping version numbers, etc. ;)

**Comment by ahankinson** [comment]
I was half-kidding -- this seems like a pretty useful thing to have, so if you can do it for cantus, etc. then it should be easy to integrate into the gulp system for diva.

**Comment by wabain** [comment]
Cantus is kind of different because there aren't versioned releases (and AFAICS there don't need to be) but doing it for Diva is no problem.
