### ISSUE TITLE
Refactor key scroll implementation

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#280]
[This `if` statement](https://github.com/DDMAL/diva.js/blob/9b78df65805e7e7f8a8ae9d68bf30260643e0486/source/js/diva.js#L1820) could use some love. It's really long, so it's hard to tell what should be inside the key/space scroll stuff (like is [this really supposed to be part of this block](https://github.com/DDMAL/diva.js/blob/9b78df65805e7e7f8a8ae9d68bf30260643e0486/source/js/diva.js#L1888)?

Refs #260

**Comment by ahwitz** [comment]
fwiw, https://github.com/DDMAL/diva.js/commit/d6ff8688cf50ffae16c8618bba46006dbf506f51 helped this but may not have solved it completely. Pretty sure that commit is "what we looked at earlier."

**Comment by ahankinson** [comment]
Ah, thanks. I guess I was looking at master, not develop.

There's still a few problems, though -- I find it hard to read through the `mobileWebKit` support here, since it's inside a big `if` block. Perhaps this can be refactored into a separate function.

It does look like this addresses the problem @wabain noticed, so perhaps #260 and DDMAL/cantus#105 will be fixed when Diva is updated to 4.0.
