### ISSUE TITLE
Use feature detection for mobile support

### ISSUE THREAD

**Issue by wabain** [DDMAL/diva.js#282]
Following up on today's [other issues](https://github.com/DDMAL/diva.js/pull/281) with mobile support...

Currently mobile support is enabled whenever `window.orientation` is defined, which AFAICT isn't the case for Internet Explorer or Gecko based user agents. Where it makes sense, those should be supported as well.

Most of the uses of the `window.orientation` test are concerned with touch events. Those should probably be detecting those directly, particularly given the introduction of touch-enabled desktop devices.

The uses that don't concern touch events are:

 1. [This iPad-specific problem](https://github.com/DDMAL/diva.js/blob/350b34044bb0b621ff0e51df4c33bc8289947260/source/js/diva.js#L1264) ([original issue](https://github.com/DDMAL/diva.js/issues/163)) with margin sizing.
 2. This [iOS-specific issue](https://github.com/DDMAL/diva.js/commit/8c3095c50ab797301b6c5aacf88e83edeb83267a) with images sizes in the canvas plugin
 3. A "[a temporary (but possibly indefinite) solution](https://github.com/DDMAL/diva.js/issues/99)" for putting up a spinner while loading on mobile devices, also in the canvas plugin
 4. Whatever [`blockMobileMove`](https://github.com/DDMAL/diva.js/blob/350b34044bb0b621ff0e51df4c33bc8289947260/source/js/diva.js#L35) is supposed to do, maybe. @magoni and I aren't really sure what that's for.

Items 1 and 2 could keep using `window.orientation` (although there might be a neater Apple-specific test). The others uses would probably benefit from testing something more general.

**Comment by magoni** [comment]
In terms of detection for events, it might be ideal to figure out a way of implementing both mouse and touch events alongside each other so that users with touch-enabled desktop devices can choose whether to use their mouse or touch surface.

**Comment by ahankinson** [comment]
Are touch events and mouse events different in Javascript?

**Comment by wabain** [comment]
Yes - this is one of those things where there are a couple similar but distinct implementations. Some things like click events get fired for both, but `mousedown`, `mouseup` and so on don't.

**Comment by magoni** [comment]
Fixed via 2f1c90bd8a91e1ad7bd0b1d83cc6e81feb98262d.
