### ISSUE TITLE
imageDir in IIIF example?

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#287]
Is the imageDir parameter needed in this example? I thought that would be in the manifest.

https://github.com/DDMAL/diva.js/wiki/Installation#the-html-file

**Comment by magoni** [comment]
If you scroll down a bit it says
> If you are using IIIF (with your own images or an existing external repository), just set objectData to the URL of the Manifest and omit the iipServerURL and imageDir settings.
I'll try to make it clearer from the beginning of the example.

**Comment by ahankinson** [comment]
Yeah... IIIF and "old-style" gets a bit confused in this documentation.

**Comment by magoni** [comment]
Revised, hopefully this is less ambiguous now. https://github.com/DDMAL/diva.js/wiki/Installation
