### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by musicus** [DDMAL/diva.js#293]
The _Launch Cantus_ button within the _Cantus ultimus_ section on the [http://ddmal.github.io/diva.js/try/ page](http://ddmal.github.io/diva.js/try/) should link to the same page as the [link](http://cantus.simssa.ca/manuscript/133/) of the image above the button.

**Comment by magoni** [comment]
Fixed via https://github.com/DDMAL/diva.js/commit/46c7f5cfa751a43c8a5de77c762858d1f4532f42

**Comment by musicus** [comment]
:100:
