### ISSUE TITLE
JavaScript Loading Time

### ISSUE THREAD

**Issue by musicus** [DDMAL/diva.js#294]
The initial JavaScript loading time is longer than expected when choosing to launch any of the examples in the [Try](http://ddmal.github.io/diva.js/try/) section, i.e. the script has not been previously cached by a browser. Once cached it's fine.

**Comment by ahankinson** [comment]
How long would you expect?

Do you want us to try and speed up the Internet? (I'll try pedalling faster! :)

**Comment by musicus** [comment]
Yes, ... please?

**Comment by ahankinson** [comment]
My question still stands though -- why is it slow? Is it your connection speed? Minimized, Diva is just 80.5KB, so I don't think that's a problem. What do you expect? What are you seeing instead?

It loads fine for me after clearing my cache, so I'm not sure if what you're seeing is isolated to your machine, or the fact that it works is isolated to mine.

**Comment by ahwitz** [comment]
5MB/s internet and 2GB of RAM, interface loads fine though images load slightly slower as expected.

**Comment by musicus** [comment]
I was only concerned about it, since it took quite a bit of time to load this morning on the wireless connection here at the lab (not the the wired connection). The _speed daemon_ and _plays well with other_ images load slowly, the images on the http://ddmal.github.io/diva.js/try/ load slowly, and I found the performance to be rather slow when initially loading the _Default_ page from the _Try_ page. Could be the JavaScript, could be the CSS, or just the seize of the images, or I was being extremely impatient this morning...

**Comment by ahankinson** [comment]
If you could clear your cache and give us some benchmarks that would be handy.

**Comment by musicus** [comment]
I ran http://ddmal.github.io/diva.js/ and http://ddmal.github.io/diva.js/try/ through  https://developers.google.com/speed/pagespeed/insights/ and it offered some suggestions (not benchmarks per se).
