### ISSUE TITLE
URLs are broken

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#298]
Getting the URL for the state of the viewer seems to be broken.

http://ddmal.github.io/diva.js/try/single.html#v=b&z=4&n=5&i=Bm%20009&y=-3826&x=2879

**Comment by magoni** [comment]
As far as I can tell, the issue is specific to Safari. From my tests, the state is being accurately reproduced in Chrome, but on Safari the viewer stays on the first page.

**Comment by magoni** [comment]
Good catch, we weren't testing the case where page/canvas labels contain non-ASCII characters. Creating an issue to add IIIF Presentation-related unit tests.
