### ISSUE TITLE
Tests - Add IIIF Presentation tests

### ISSUE THREAD

**Issue by magoni** [DDMAL/diva.js#299]
Add tests with a IIIF manifest for checking IIIF features, i.e. proper handling of manifests.

**Comment by jeromepl** [comment]
When looking at the code coverage, I don't see any code related to IIIF (apart from the plugins) that isn't already covered. Even the 'parse-iiif-manifest.js' has an 85% coverage. Maybe this was already done by someone else recently. Closing this.
