### ISSUE TITLE
Support passing in a manifest object

### ISSUE THREAD

**Issue by wabain** [DDMAL/diva.js#300]
Now that Diva supports IIIF, its image manifests are of interest to code outside the viewer, for instance for displaying the Presentation API metadata. As a result, it would be useful to be able to pass in a previously fetched manifest object instead of having Diva fetch it from a URL. This strikes me as a feature that could also be useful for testing.

A public getter for the manifest would presumably be helpful as well, but I don't have an immediate use case for it.

**Comment by magoni** [comment]
That makes a lot of sense! I'll add getter and setter methods that take and return a Javascript object representing a IIIF manifest, as well as the option to pass the manifest as an object into the constructor.

**Comment by magoni** [comment]
Nice, thanks! Adding Presentation API unit tests will be definitely be easier now also.

**Comment by magoni** [comment]
I'll
- [ ] update the relevant documentation
