### ISSUE TITLE
Random Highlight Link - Demo Page

### ISSUE THREAD

**Issue by musicus** [DDMAL/diva.js#307]
The _A demonstration of the highlight plugin_ link seems strange, since, when landing on the page it highlights random regions. Replace it with the _IIIF Highlight Pages_ demo.

**Comment by fujinaga** [comment]
Whatever you do, please do not break: 
http://ddmal.github.io/diva.js/try/iiif-highlight-pages/

It’s an excellent site to demonstrate the wonders of IIIF!

Thanks!

**Comment by musicus** [comment]
We want to draw attention to exactly that link with this issue.

**Comment by musicus** [comment]
:neckbeard:

**Comment by musicus** [comment]
:lipstick:

**Comment by AFFogarty** [comment]
:pig: :lipstick:
