### ISSUE TITLE
Double click events not received immediately after zoom

### ISSUE THREAD

**Issue by magoni** [DDMAL/diva.js#309]
During and for a short period after zooming via double-click, the `diva-inner` element doesn't receive click events. This means that quick successive zooms (double-clicking and then double-clicking again very shortly after) are prevented.

This issue does not affect zooming with the +/- zoom buttons.

**Comment by EricHanLiu** [comment]
Somewhat related to #456 

This was present in Diva 5 as well, so not related to the zoom animation changes

**Comment by EricHanLiu** [comment]
#456 fixed by disabling buttons during animation - zoom shouldn't be possible during an animation
