### ISSUE TITLE
IIIF Highlight Demo is not correct

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#310]
Currently the IIIF highlight demo is using a manifest that only contains annotations for one page.

However, we have a manifest that contains the annotations for all the pages, available at: http://dev.simssa.ca/iiif/stgallen_390_annotated.json

The IIIF Highlight demo should be changed to use the more complete version. The annotations are already available on the GitHub server at: https://github.com/DDMAL/diva.js/tree/gh-pages/try/annotations

**Comment by fujinaga** [comment]
I'm giving talks this week.
Please do not break the original demo site.

Ich

**Comment by ahankinson** [comment]
It can wait.

**Comment by fujinaga** [comment]
I’m done with my demos for a while; so you can go ahead and make the changes.

**Comment by wabain** [comment]
I can take a look at this Monday.

**Comment by wabain** [comment]
Should I update the manifest on ddmal.github.io to include the annotations, or point the demo toward the manifest on dev.simssa.ca?

**Comment by ahankinson** [comment]
Update the manifest on ddmal.github.io

**Comment by wabain** [comment]
So there's already a complete manifest under `try/iiif-highlight-pages`, but 6587bc5ef868a4b8854a31dd72865d16cb864733 pointed Diva towards an incomplete manifest under `try/iiif-highlight`. Not really sure why those separate directories exist, but for now I changed the URL.
