### ISSUE TITLE
Extra horizontal margins on initial load

### ISSUE THREAD

**Issue by wabain** [DDMAL/diva.js#312]
When St. Gallen 390 (and presumably other manifests of suitable size) is loaded in single-page view in a large window, the margins are wide enough that there's a bit of room to scroll horizontally to the right. If you zoom in and out again, those extra margins go away, which I'm guessing is the desired behaviour. This happens both for v4.1.0 and the current 5.0 dev version.

My first guess is that the vertical scroll bar isn't being taken into account when initially setting the width of `diva-outer`.

**Comment by ahankinson** [comment]
I think there's some tricking stuff waiting here for you -- I've been through this, and the width and height of the elements aren't available to you at initialization. One of the parameters (I can't remember which) is null until you zoom or resize.

**Comment by wabain** [comment]
Sounds fun!

**Comment by wabain** [comment]
So this is pretty convoluted, but basically the scrollbar width wasn't being taken into account when the viewport dimensions were first cached. A handful of the hasparam tests relied on that (since they use a center-based coordinate system) so I'm just changing the expected values for those.

**Comment by wabain** [comment]
This will have to wait until I can fix some bugs in the way I decide whether there will be a scroll bar.
