### ISSUE TITLE
Support Presentation API 2.1 features

### ISSUE THREAD

**Issue by wabain** [DDMAL/diva.js#313]
The draft of the next release of the Presentation API is getting pretty stable. It makes sense to start looking towards implementing the [new features](http://iiif.io/api/presentation/2.1/change-log/).

**Comment by wabain** [comment]
New features:

- [ ] `rendering`: "Link to alternate representations of Resources." **Expose in IIIF metadata plugin**
- `navDate`: "A date that the client can use for navigation purposes when presenting the resource to the user in a time-based user interface." **No immediate use case for this.**
- Comment annotations on non-canvas resources. **No immediate use case**, as far as I can tell.
- [ ] `viewingHint: facingPages`: **Special-case book view for this.**
- `viewingHint: multi-part` for collections and the `members` property. **No use case** since Diva doesn't expose collection-browsing functionality.

**Comment by ahankinson** [comment]
Prezi 2.1 is already supported. Closing.
