### ISSUE TITLE
Audit public methods

### ISSUE THREAD

**Issue by wabain** [DDMAL/diva.js#314]
Diva has a number of public methods which seem to have niche use cases or to be slight variations on more general functionality (looking at you, `getCurrentPageDimensionsAtCurrentZoomLevel` and `gotoPageByNumber`). We should see what methods are actually being used by DDMAL code bases and what could probably be removed.

**Comment by ahwitz** [comment]
For those two:

Pretty sure the former was used in the older version of the St. Gall editor, but it seems not to be used [at all any more](https://github.com/search?utf8=%E2%9C%93&q=getCurrentPageDimensionsAtCurrentZoomLevel&type=Code&ref=searchresults). I take full blame for the existence of that method and think it should be smashed into the ground.

The latter was from before my time and is used in [a bunch of older projects](https://github.com/search?p=1&q=gotopagebynumber&ref=searchresults&type=Code&utf8=%E2%9C%93), although I've personally been trying to use ByIndex instead.

**Comment by wabain** [comment]
I hadn't even thought to do a search across all of Github --- I assumed there would be a bunch of irrelevant results unless I restricted it to DDMAL.

**Comment by ahwitz** [comment]
I'd started with just an org search and tried it out of curiosity for the first one because of how long it was. Turned out to work well for both.

**Comment by wabain** [comment]
I didn't find time to boil this down as much as I wanted, so I'm posting it as a mix of recommendations and observations.

# Core

Things to keep:

* `getItemTitle`
* `gotoPageByIndex`, `gotoPageByName`
* `getNumberOfPages`
* `isReady`
* `getCurrentPageIndex`
* `getInstanceSelector`, `getInstanceID`, `getSettings`
* `getMaxZoomLevel`, `getMinZoomLevel`, `getMaxZoomLevelForPage`
* `getZoomLevel`, `setZoomLevel`
* `zoomIn`, `zoomOut`
* `toggleFullscreenMode`, `enterFullscreenMode`, `leaveFullscreenMode`
* `changeView`, `enterGridView`, `leaveGridView`
* `getCurrentURL`, `getURLHash`
* `getPageDimensionsAtZoomLevel` (used by highlight demo), `translateToMaxZoomLevel`, `translateFromMaxZoomLevel` (used by Cantus Editor, highlight plugin). Needed for some niche use cases like dynamically drawing boxes overlaid on the viewer.
* `getState`, `setState`
* `getPageImageURL`
* `isPageInViewport`
* `enableScrollable`, `disableScrollable`
* `toggleOrientation`, `isVerticallyOriented`
* `changeObject`
* `activate`, `deactivate`
* `destroy`

Things we could probably get rid of or change, but don't really need to:

| Method | Real-world usage | Notes |
|:------:|------------------|----------|
| getCurrentPageDimensionsAtCurrentZoomLevel | ? | Nothing wrong with this, besides it being awkwardly long
| getCurrentPageFilename, getFilenames | Cantus Ultimus, meix | "Filename" is an awkward fit with IIIF. Is it a unique identifier (`@id`) or a public facing name (`label`)? Something to review at some point.
| closePopups | None? | Kind of awkward in that there's no underlying API to *close* popups; it just hides them until some event is triggered to actually close them
| getPageOffset | Partbook viewer, meix | I'm not sure there's any scenario where using an absolute offset relative to the view of the Diva document is actually the best approach. Generally viewport position should be handled through page-relative offsets, which handle zoom level changes more gracefully.
| getCurrentPageOffset | None? | Same as above

Things to remove or change:

| Method | Real-world usage | Proposal |
|:------:|------------------|----------|
| gotoPageByNumber, getCurrentPageNumber | Cantus Ultimus, probably others | Deprecate in 5.0 in favour of `__ByIndex`, remove in 6.0
| inViewport | None? | Uses a 1-based page number, breaks from the usual naming convention of `is__` for public methods returning booleans. Not sure exactly what to replace it with.
| isPageLoaded | Highlight plugin | Deprecate and make an alias of isPageInViewport in 5.0, remove in 6.0
| getPageIndex | ? | This works with filenames for legacy manifests and I think IIIF labels, but the method name is overgeneral and it's not clear how it should work with IIIF labels vs IDs. It should print a warning when the upgrade path is clear.
| getPageDimensionsAtCurrentGridLevel || I think this either will be or already is a synonym for getPageDimensionsAtCurrentZoomLevel: grid view does/should have a zoom level, it's just read-only. Deprecate and alias.
| getPageIndexForPageXYValues | meix.js | Confusingly named ("page" refers to a page in the Diva document and then the browser window). My instinct is that this functionality should really be exposed for viewport-relative coordinates rather than the browser window, but I don't have any strong justification. Refs #249.

# Autoscroll plugin

Keep:

* startScrolling, stopScrolling, toggleScrolling
* changeScrollSpeed
* enableManualScroll, disableManualScroll

The `changeRefresh` method controls (I think) the scroll refresh rate. It seems to me that it's confusingly named, since it's not obvious it's about autoscrolling. I also the current implementation is broken, since the value gets overwritten in `updatePixelsPerScroll`. Maybe get rid of this?

# Highlight plugin

Keep:

* highlightOnPage, highlightOnPages (takes an awkward argument format, but there's no strong need to change it)
* gotoHighlight, gotoNextHighlight, gotoPreviousHighlight
* resetHighlights

I can't find anything using `removeHighlightsOnPage`, and I'm not sure what the use case for it would be, since it's not granular enough to remove arbitrary highlights without a full reset.

# IIIF highlight plugin

Has most of the same methods as the highlight plugin, plus `showHighlights` and `hideHighlights`, which do the same thing as clicking the annotations button.

# Page alias plugin

The page alias plugin exposes the following methods, none of which are used as far as I can tell: `getAliasForPageIndex`, `getPageIndexForAlias`, `getPageIndicesForAlias`, `getCurrentAliasedPageIndex`, `gotoPageByAliasedNumber`. Refs #337.

(Cantus Ultimus implements some logic similar gotoPageByAliasedNumber, with differences motivated by #265.)

**Comment by jeromepl** [comment]
Changes I made on public methods, following @wabain 's recommendations:

### Deprecated:
- gotoPageByNumber() —> Use gotoPageByIndex()
- getCurrentPageNumber() —> Use getCurrentPageIndex()
- isPageLoaded(pageIndex) —> Use isPageInViewport(pageIndex)
- getPageDimensionsAtCurrentGridLevel(pageIndex) —> Use getPageDimensionsAtCurrentZoomLevel(pageIndex)

### New:
- getPageDimensionsAtCurrentZoomLevel(pageIndex): Returns the dimensions of a given page at the current zoom level, no matter what view the document is in.

### Name change:
- inViewport —> isRegionInViewport

### Functionality change:
- getCurrentPageDimensionsAtCurrentZoomLevel(): Now also works in grid view.
- isRegionInViewport (old inViewport): Now uses pageIndex instead of pageNumber
- getPageIndexForPageXYValues(pageX, pageY): Now returns -1 (instead of false) if no page was found.

**Comment by jeromepl** [comment]
New changes after I added support for 'non-paged' pages:

### New public methods:
- toggleNonPagedPagesVisibility()
- showNonPagedPages()
- hideNonPagedPages()

### Changes to public methods:
- isValid: Now also checks if the page is paged or if non-paged pages are visible.

### New settings:
- enableNonPagedVisibilityIcon: show or hide the icon in the toolbar that toggles visibility of non-paged pages. Note that the icon is automatically hidden if there are no non-paged pages in the current document. **Default**: true
- showNonPagedPages: Whether pages tagged as ‘non-paged’ (in IIIF manifests only) should be visible. **Default**: false

**Comment by jeromepl** [comment]
I think this is as far as I am going to go with these changes. Closing.
