### ISSUE TITLE
Loading spinners cause constant repaints

### ISSUE THREAD

**Issue by wabain** [DDMAL/diva.js#319]
Currently Diva places a loading gif on the background of page elements which is hidden once the images load. Unfortunately since the gif is still there even once it's hidden, the browser is forced to constantly repaint the page area. It would probably be possible to work out when the gif is out of view and then remove it, but at least temporarily I'm going to just get rid of it.

**Comment by ahankinson** [comment]
Is this in the new canvas implementation? Or in the previous div implementation?

**Comment by wabain** [comment]
It's in both. It looks like it's been there since 2.0: https://github.com/DDMAL/diva.js/commit/b10027ffe41258db10c44dafd4d69c5155fcf21e

It's not a huge problem, but removing it had a noticeable effect on the frame rate.

**Comment by wabain** [comment]
Actually that's not the right commit, but it's been there for a long time.

**Comment by ahankinson** [comment]
Yeah, we put it there so that people would feel like something was happening.... It would be nice to not remove any loading indication entirely, though.

**Comment by wabain** [comment]
Yeah, I'll keep this open until I find a better solution.

**Comment by ahankinson** [comment]
This has been removed in Diva 6 and is no longer a problem.
