### ISSUE TITLE
Expose jQuery-free API

### ISSUE THREAD

**Issue by wabain** [DDMAL/diva.js#324]
Client code shouldn't need to use jQuery to use Diva. Supporting code without jQuery should be pretty easy:
- [ ] Ensure options which expect a jQuery object work with a plain DOM element
- [x] Expose high-level methods on the `diva` export. Something like:
  
  ``` js
  diva.create(elem: Element, options: Object): Viewer
  diva.find(elem: Element): ?Viewer
  ```
  
  These correspond pretty directly to `$(..).diva(options)` and `$(..).data('diva')`

**Comment by ahwitz** [comment]
:+1:

**Comment by ahankinson** [comment]
The removal of jQuery is part of Diva 6.

**Comment by EricHanLiu** [comment]
What needs to be done here? Seems like no options expect a jQuery object anymore

**Comment by ahankinson** [comment]
^^^ See my comment above. You can close this. Easy win.
