### ISSUE TITLE
Support multiple views of a canvas

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#335]
[IIIF 6.3: Choice of Alternative Resources](http://iiif.io/api/presentation/2.1/#choice-of-alternative-resources)

**Comment by ahankinson** [comment]
For IIIFv3, this would be supported by providing multiple `AnnotationPage` objects on a `Canvas`, each with an `Annotation` and an `Image` associated with it.

**Comment by EricHanLiu** [comment]
How should the option to select between different views be presented to the user?

Also, since this feature seems to be possible for any given page, how would Diva be able to render multiple versions of the same page for each and every page?

**Comment by EricHanLiu** [comment]
Merged
