### ISSUE TITLE
Restrict viewer state properties exposed through settings object

### ISSUE THREAD

**Issue by wabain** [DDMAL/diva.js#336]
They should be a subset of the properties exposed in [Diva 4.1](https://github.com/DDMAL/diva.js/blob/1e8c04c661b5c84b88a7244cc1350c80626c8fbb/source/js/diva.js#L80).

**Comment by EricHanLiu** [comment]
Currently in Diva 6 all the viewer core settings are exposable through the `diva.settings` object. I believe this is how it should be, and don't see a need for this change - likely this issue is outdated for the current Diva 6 code logic
