### ISSUE TITLE
Fix/reintegrate pagealias plugin

### ISSUE THREAD

**Issue by wabain** [DDMAL/diva.js#337]
At some point I broke the page alias plugin, which was relying on internal callback methods from the toolbar being conveniently exposed to plugins. I think the best approach might be to move page aliasing functionality into the core since it modifies core behaviour instead of adding new functionality and at some point will need to interact with IIIF labels.

**Comment by ahankinson** [comment]
@jeromepl this is done, correct?

**Comment by jeromepl** [comment]
I'll run a quick test once I get back, but I haven't touched any code in that plugin recently...
I completely missed this issue.

**Comment by jeromepl** [comment]
pagealias plugin is not working at all at the moment. Working on a fix.

**Comment by ahwitz** [comment]
good luck

**Comment by ahankinson** [comment]
https://www.youtube.com/watch?v=SmHeP9Sve48

**Comment by jeromepl** [comment]
How should this be released? 5.0.1?

New documentation to add:

### New Settings:
- **pageAliases**: An object mapping specific page indices to their alias. (Has priority over the 'pageAliasFunction' setting.
- **pageAliasFunction**: A function mapping page indices to an alias. If false is returned, default page number is displayed.
_If none of those settings are specified when instantiating Diva, the regular page number will be displayed in the toolbar._

### New Public Methods:
- **getAliasForPageIndex**: Returns the first of these three that resolves to boolean `true` (Else the function will return `false`):
         -Explicit alias as defined in pageAliases
         -Result of pageAliasFunction
         -originalPageIndex + 1 (to simulate the original mapping)
- **getPageIndexForAlias**: Returns the first page index found for a given aliased number or false if not found.
- **getPageIndicesForAlias**: Returns array of page indices for a given aliased number. Returns an empty array if none are found.
- **getCurrentAliasedPageIndex**: Same as `getAliasForPageIndex` but uses the current page index automatically.
- **gotoPageByAliasedNumber**: Go to a specific page based on its alias.

**Comment by wabain** [comment]
If you're making a 5.0.1, think you could add me to the authors list? :)

**Comment by ahankinson** [comment]
Aren't you already?

**Comment by ahankinson** [comment]
I would delete the tag and release it again.

**Comment by jeromepl** [comment]
Oh, something else I forgot :O need to add people to the AUTHORS file

**Comment by ahwitz** [comment]
ahwitz[at]gmail.com here

**Comment by jeromepl** [comment]
@wabain what is your preferred email address?

**Comment by ahankinson** [comment]
We can probably replace e-mail addresses with GitHub usernames / GitHub user links?

**Comment by jeromepl** [comment]
That might be better, yeah. Except for "Project Coordinator" (Ich) probably

**Comment by ahankinson** [comment]
You can move me to project co-ordinator and use my e-mail address.

**Comment by jeromepl** [comment]
I am only missing Laurent Pugin. He does not seem to appear here: https://github.com/DDMAL/diva.js/graphs/contributors

**Comment by ahwitz** [comment]
github.com/lpugin

**Comment by ahankinson** [comment]
Laurent did a lot on Diva in the early days -- he and I worked through the layout system, even though I did all the coding.
