### ISSUE TITLE
submit button id attribute

### ISSUE THREAD

**Issue by milnerm** [DDMAL/diva.js#338]
add id attribute to form.diva-goto-form input[type='submit']

**Comment by ahankinson** [comment]
I believe this is fixed in develop.

https://github.com/DDMAL/diva.js/blob/develop/source/js/toolbar.js#L350

@jeromepl could you confirm and close if so?

**Comment by jeromepl** [comment]
I don't think it is fixed. If you look at https://github.com/DDMAL/diva.js/blob/develop/source/js/toolbar.js#L360 you can see that no ID attribute is defined for the input[type="submit"] element. Line 350 refers to the input[type="text"], not the submit button.

**Comment by ahankinson** [comment]
Ah, right. So this should be added for the next release.
