### ISSUE TITLE
Error when one of the canvases in IIIF manifest has sizes below 128x128

### ISSUE THREAD

**Issue by jeromepl** [DDMAL/diva.js#344]
This error is caused by `getMaxZoomLevel` in the IIIF parser, since the calculation returns a negative number, which is then used to create an array of negative size.
Here is a [link to the code](https://github.com/DDMAL/diva.js/blob/master/source/js/diva.js#L2800).

Furthermore I am unsure if the behaviour of max zoom level is really what we want. For example, if all canvases are of size 4000x4000 except for a smaller one of size 200x200, then the entire document will be displayed really zoomed in **without the option to zoom out**, which is really annoying.

Thanks to @belljustin for finding this.

![screen shot 2016-07-15 at 3 43 08 pm](https://cloud.githubusercontent.com/assets/7671307/16886524/e3e901de-4aa2-11e6-8468-d07687f43d04.png)

**Comment by ahankinson** [comment]
Has this been addressed? If not, you can put it on the 6.0 Milestone

**Comment by EricHanLiu** [comment]
Issue seems to still be present in Diva6. Using [this manifest](https://iiif.bodleian.ox.ac.uk/iiif/manifest/caeb212c-a639-41da-a42a-60f6b05a0d0b.json) and setting the height/width of the canvas to anything above 128x128 works just fine, but once both parameters are under 128 I get the following error

```javascript
(viewer-core.js:265) 
Uncaught (in promise) TypeError: Cannot read property 'w' of undefined
    at ViewerCore.getPageData (viewer-core.js:265)
    at ViewerCore.getXOffset (viewer-core.js:749)
    at ViewerCore.setManifest (viewer-core.js:1162)
    at Diva._loadObjectData (diva.js:233)
    at diva.js:164
```

I can do 128 by anything, just when they're both under 128 is when the error is thrown

**Comment by EricHanLiu** [comment]
Can fix by just returning 0 as maxZoom if the canvas' `largestDimension < 128`. Not sure about the second concern 
> Furthermore I am unsure if the behaviour of max zoom level is really what we want
