### ISSUE TITLE
Remove deprecated code from Diva 5

### ISSUE THREAD

**Issue by jeromepl** [DDMAL/diva.js#350]
The Diva 5.0 release is getting close and with it comes a lot of new deprecated methods. For Diva 6.0, those should all be completely removed.

Here is the list of everything deprecated in Diva 5:
- Support for IIP manifests
- **Public methods**: (explanation of replacements can be found in console.warn() ’s)
  - gotoPageByNumber
  - getCurrentPageNumber
  - isPageLoaded
  - getPageDimensionsAtCurrentGridLevel

**Comment by EricHanLiu** [comment]
These deprecated methods have already been removed. Removed two variables that were only related to IIP manifests.
