### ISSUE TITLE
Manifests in demo do not load

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#353]
In the `iiif-external.html` demo, the harvard and yale manifests do not load. Perhaps we can find replacements for them (Internet Archive or Gallica?)

**Comment by jeromepl** [comment]
The last 2 manifests are loading fine, it is the first two that we need to replace. Maybe we could use these:
http://iiif.archivelab.org/iiif/worksofhenryfiel015844mbp/manifest.json
and the Salzinnes manifest?
Just quickly found the first one on Internet Archive.

**Comment by jeromepl** [comment]
This one on Gallica is also nice: http://gallica.bnf.fr/ark:/12148/btv1b550076223/f14.item
