### ISSUE TITLE
Check variable scoping

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#356]
Shouldn't [these variables](https://github.com/DDMAL/diva.js/blob/develop/source/js/diva.js#L429) be locally scoped (have a `var` declaration)?

**Comment by ahankinson** [comment]
Hm, nevermind. `viewerState` seems to be a global object?

**Comment by jeromepl** [comment]
Yeah, `viewerState` and `settings` are used so much in the entire diva.js file that they seem to just be retrieved once from the `viewerCore` in the `init()` method.
