### ISSUE TITLE
Details box can extend past screen top

### ISSUE THREAD

**Issue by workergnome** [DDMAL/diva.js#362]
For very long details, on smaller screens, the detail box can extend off the top of the screen, and there's no way to remove it (that I could see.)

![screen shot 2016-08-26 at 10 39 25 am](https://cloud.githubusercontent.com/assets/34536/18009262/70aa782c-6b79-11e6-9b49-2c37cc5ade52.png)

**Comment by EricHanLiu** [comment]
Fixed with new metadata plugin
