### ISSUE TITLE
Re-render the diva js

### ISSUE THREAD

**Issue by byzheng** [DDMAL/diva.js#363]
I am integrating diva.js with my web application (i.e. Shiny in R) and display multiple image sets (Serve as iiip server). Currently I can show individual image set, but cannot dynamically change to another image set. It seems diva object cannot change after initialisation. 

I have tried to use the destroy function but get an error: 

    Uncaught TypeError: Cannot read property 'clientHeight' of null

How do I switch to another dataset? 

Here is my example js scripts, which just give an example to show another dataset after initialisation.

	$(document).ready(function() {
		$('#diva-wrapper').diva({
			enableAutoHeight: true,
			fixedHeightGrid: false,
			iipServerURL: "/iipsrv/iipsrv.fcgi",
			objectData: "/data/tmp/iip/iip_r/ImageIIP.json",
			imageDir: "ImageTiles1",
			enableCanvas: true,
			enableDownload: false,
			inGrid: true
		});
		
		var diva = $('#diva-wrapper').data('diva');
		var old_style = $('#diva-wrapper').attr('style')
		var old_class = $('#diva-wrapper').attr('class')
		diva.destroy();
		$('#diva-wrapper').attr('style', old_style)
		$('#diva-wrapper').attr('class', old_class)
		$('#diva-wrapper').diva({
				iipServerURL: "/iipsrv/iipsrv.fcgi",
				objectData: '/data/tmp/iip/iip_r/ImageIIP2.json',
				imageDir: 'ImageTiles2',
			enableCanvas: true,
			enableDownload: false,
			inGrid: true
			});
				
		
	});

**Comment by ahankinson** [comment]
The most straightforward way is to destroy the Diva instance and then re-initialize. 

```
var inst = $("#diva-wrapper").data('diva');
inst.destroy();
```
... then re-initialize with new object data.

The other way to do it is to use the `changeObject` public method:

```
var inst = $('#diva-wrapper').data('diva');
inst.changeObject("/path/to/ImageIIP2.json");
```

**Comment by ahankinson** [comment]
BTW, we're deprecating the older (proprietary) Diva JSON format in favour of IIIF manifests.

**Comment by byzheng** [comment]
I have tried destroy method, and can view the new image set, but the object height and width are not correct with an error message:

     Uncaught TypeError: Cannot read property 'clientHeight' of null

What's the new format for IIIF manifests? Could I use it now?

**Comment by ahankinson** [comment]
The new IIIF manifests actually follow a standard format. The spec is available here:

http://iiif.io/api/presentation/2.1/

In the Diva demos we ship a few example IIIF manifests:

https://github.com/DDMAL/diva.js/blob/master/demo/beromunster-iiif.json

We actually have a demo of replacing the object data. The code is here:

https://github.com/DDMAL/diva.js/blob/master/demo/diva/iiif-external.html#L20

and the demo is here:

http://ddmal.github.io/diva.js/try/demo/iiif-external.html

**Comment by byzheng** [comment]
Thanks for your quick reply. is there any script to generate new iiif json file? The process.py seems only generate the old format. 

BTW: I am working on the R script to generate the required json file in parallel. It will be really useful for large amount of images. Happy to contribute if you are interesting.

**Comment by ahankinson** [comment]
There are a number of scripts contributed by the IIIF community.

https://github.com/IIIF/awesome-iiif#presentation-api-libraries

At this point I would probably advise that, going forward, you should concentrate on building IIIF manifests. Support for the Diva-specific JSON format will be removed in the next release. 

I notice that there is no R library for generating IIIF manifests, so if you're more comfortable in that language than in, say, Ruby, Python, or JavaScript, you can contribute your work to that community. The advantage of doing that is that your manifests become usable for more than just Diva: Mirador and the Universal Viewer also support IIIF manifests.

**Comment by byzheng** [comment]
Thanks for your suggestion. I have figured out to generate iiif meta files in R.
