### ISSUE TITLE
Click event on each page

### ISSUE THREAD

**Issue by byzheng** [DDMAL/diva.js#364]
Is it possible to listen on click event on  each page? I would like to return the page number of name when I click each page (not double click).

**Comment by ahankinson** [comment]
You can try the [getPageIndexForXYValues](https://github.com/DDMAL/diva.js/blob/master/source/js/diva.js#L941) method.

**Comment by byzheng** [comment]
Thanks for your suggestion. It seems there is a bug in the getPageIndexForXYValues. This function always return to -1 no matter where I clicked. This is my test code.

    var diva = $('#diva-wrapper').data('diva');
     $('#diva-wrapper').click(function(e){
           alert(diva.getPageIndexForPageXYValues(e.pageX, e.pageY));
    });

After debugging into diva.js, the line return an empty array even I have 7 pages on my screen:

    var pages = document.getElementsByClassName('diva-page');

Not sure how to fix it.

**Comment by byzheng** [comment]
Just for clarification of my question. I am showing images from UAV using diva.js and would like to get the file name when I click a image (a page) in grid, book and document view, then use the filename for other process. `getPageIndexForPageXYValues` seems only to work with book or document as I don't find the object `diva-page` in grid view.

**Comment by byzheng** [comment]
I have wrote some codes to return the pageIndex from pageX and pageY which is only working for grid mode. It seems to work according to my test. Happy to submit a pull request if you think  these codes are correct and worth to merge.

	this.getPageIndexForPageXYValues = function(pageX, pageY)
	{
		//get the four edges of the outer element
		var outerOffset = viewerState.outerElement.getBoundingClientRect();
		var outerTop = outerOffset.top;
		var outerLeft = outerOffset.left;
		var outerBottom = outerOffset.bottom;
		var outerRight = outerOffset.right;

		//if the clicked position was outside the diva-outer object, it was not on a visible portion of a page
		if (pageX < outerLeft || pageX > outerRight)
			return -1;

		if (pageY < outerTop || pageY > outerBottom)
			return -1;

		if (settings.inGrid) {
			// Calculate the position of top left corner of the current page 
			var yOffset = outerOffset.height / 2 - viewerState.verticalOffset + outerTop;
			var xOffset = outerOffset.width / 2 - viewerState.horizontalOffset + outerLeft; 
			// Get the current page index
			var currentPageIndex = this.getCurrentPageIndex();
			// Get the current page dimension
			var pageDimension = this.getPageDimensionsAtCurrentZoomLevel(currentPageIndex);
			// Calculate the row and column index relative to current page index
			var colIndex = Math.floor((pageX - xOffset) / pageDimension.width);
			var rowIndex = Math.floor((pageY - yOffset) / pageDimension.height);
			// Using the pages per row to calculate the page index
			var clickPageIndex = rowIndex * settings.pagesPerRow + colIndex + currentPageIndex;
			if (clickPageIndex > viewerState.numPages) {
				return -1;
			}
			return clickPageIndex;
		}

		return -1;
	};

**Comment by ahankinson** [comment]
What happens if the view is not in grid view? It would be good to click on a page and have it return the page index number for all views.

**Comment by byzheng** [comment]
-1 will return in other views. Still working on other views, but I don't have urgent requirement for this feature, So it may take me a while  to implement it.

**Comment by ahankinson** [comment]
OK, thanks.
