### ISSUE TITLE
PageDidLoad not firing

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/diva.js#365]
The wiki documentation says that a 'PageDidLoad' event is fired when a page has finished loading. This event does not seem to be supported even though it is documented (did own test and searched for the Event in the code - it is never published).

**Comment by mrbannon** [comment]
I have to note that this event is used in the documentation as an example of the event system even though it does not seem to be implemented.

https://github.com/DDMAL/diva.js/wiki/Events-System#subscribe

**Comment by wabain** [comment]
Can confirm the publish call was removed in 6e7d285b3d1715bb47d5778b6fdaf0b1e2c0388e and not reimplemented. It looks like it never actually fired *after* the page loaded though -- just after the DOM element for the page was inserted. I don't think the old code even knew when or if the images loaded.

**Comment by EricHanLiu** [comment]
documentation issue, will be fixed in new documentation for diva6. creating a separate issue
