### ISSUE TITLE
Uncaught Error: Cannot find module "lodash.maxby" with using diva.min.js after build

### ISSUE THREAD

**Issue by jezerinac** [DDMAL/diva.js#366]
This is more of a developer question than issue.  I'm trying to get project running so I can contribute.

I have a page that runs correctly using the js from the github website:
http://ddmal.github.io/diva.js/try/js/diva.js

I have checked out the project and made a simple change to the JS and then did "gulp:build".  I copied that resulting diva.min.js in the build package and made my page reference that js instead of the github js.

When I load the page now I receive `Uncaught Error: Cannot find module "lodash.maxby"` and diva does not initialize.  I think the problem is something with my build setup or maybe just an issue with the current master.

**Comment by wabain** [comment]
Could you try running `npm install` before running gulp and see if the result is the same?

**Comment by jezerinac** [comment]
That fixed it after a major fight with node and cygwin.  Thanks!
