### ISSUE TITLE
How to enable renderer debug

### ISSUE THREAD

**Issue by jezerinac** [DDMAL/diva.js#372]
Is there a way from the console to enable the debug statements?  For example, I would like the following to produce console logs:

`
        debug('Canvas dimension change: (%s, %s) -> (%s, %s)', this._canvas.width, this._canvas.height,
            this._viewport.width, this._viewport.height);
`

**Comment by wabain** [comment]
To enable debugs for the renderer you can set `localStorage.debug = 'diva:Renderer'` and refresh the page. To enable all the debugs you can set `localStorage.debug = 'diva:*'`. There's more [here](https://www.npmjs.com/package/debug).

**Comment by jezerinac** [comment]
works thanks
