### ISSUE TITLE
Finish toolbar in fullscreen mode

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#376]
Toolbar should fade in / out when a mouse is moved so that the images are unobscured when viewing, but the controls are available to the user in fullscreen mode.

**Comment by EricHanLiu** [comment]
It should be faded out whenever the mouse is moving and come back when the mouse stops?

Or fade in when the mouse hovers over the toolbar?

**Comment by EricHanLiu** [comment]
Done

**Comment by ahankinson** [comment]
You can close issues from commits; just put "Fixes #376" in it and GH will close them for you.

**Comment by ahankinson** [comment]
Not quite done. 

When in fullscreen mode, the toolbar seems to fade in and out at random when scrolling. (on my Macbook Pro with a touch pad). 

You might want to keep it faded in when the user is scrolling as well.

Also, the timeout seems to be a bit fast. Can you increase it to 2000ms? Also, the timeout should be made a constant so that it's a non-magic number.

**Comment by EricHanLiu** [comment]
Yeah I guess with a touch pad the mouse is probably moving slightly when you start a 2 finger scroll so the toolbar timeout gets refreshed. 

I've changed it to 2000ms, I'll get it to stay visible while scrolling

**Comment by EricHanLiu** [comment]
Toolbar disappearing feature persists after leaving fullscreen mode since event listeners aren't properly removed
