### ISSUE TITLE
Diva only renders the first row of tiles to a page

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/diva.js#378]
Only part of the image is rendered when zoom > 2

**Comment by ahankinson** [comment]
Feedback: I would suggest more descriptive issue titles. The issue wasn't that Diva wasn't rendering any tiles to the screen, it was that it was only rendering the first row. So perhaps a title like: "Diva only renders the first row of tiles to a page" would be a more accurate title.

**Comment by ahankinson** [comment]
Also, don't be afraid to use labels.

**Comment by ahankinson** [comment]
It's ok to leave this open, even though it's been fixed. It will be closed when the code is merged to `master`.
