### ISSUE TITLE
disableScrollable() returns an error

### ISSUE THREAD

**Issue by zeyadhazem** [DDMAL/diva.js#392]
Error trace
```
Uncaught TypeError: this.viewerState.innerObject.hasClass is not a function
    at ViewerCore.disableScrollable (viewer-core.js:1401)
    at PixelPlugin.activatePlugin (pixel.js:127)
    at PixelPlugin.handleClick (pixel.js:106)
    at HTMLDivElement.<anonymous> (page-tools-overlay.js:53)
```

**Comment by zeyadhazem** [comment]
The bigger issue is with unbind('mousedown') not being a function (this was the way disabling drag scroll was done in Diva 5). It seems that event unsubscription necessitates passing the callback function, that might require some changes to the code (dragscroll.js and viewer-core.js). Do you think there is a less intrusive way to do it?

**Comment by ahankinson** [comment]
Can you link to the line?

**Comment by zeyadhazem** [comment]
Oops, just saw this, might be a little late but here: https://github.com/DDMAL/diva.js/blob/develop-diva6/source/js/viewer-core.js#L1399-L1400

**Comment by ahankinson** [comment]
@EricHanLiu to check and verify if it has been fixed.

**Comment by EricHanLiu** [comment]
PR was never accepted and the branch was deleted. Added his fix now to `develop`, and can verify it has been fixed.
