### ISSUE TITLE
(Question) Is there an easy way to render a whole page on a canvas in Diva

### ISSUE THREAD

**Issue by zeyadhazem** [DDMAL/diva.js#395]
Diva only renders visible pages, but in order for Pixel.js to extract pixel data from a page, it needs the whole page to be rendered. Is there an easy way to do this through Diva?

**Comment by zeyadhazem** [comment]
A paint page at zoom level on a canvas would be perfect for my issue for example

**Comment by EricHanLiu** [comment]
Seems like this was fixed within the Pixel mechanics for handling out of view pixel data
