### ISSUE TITLE
Cannot exit fullscreen mode once the fullscreen button is clicked

### ISSUE THREAD

**Issue by PotassiumK** [DDMAL/diva.js#400]
Since the toolbar is removed on fullscreen mode, there needs to be a keyboard shortcut or some other way to exit the fullscreen mode in order to bring the toolbar back.

In Pixel.js the `F` key is used to toggle between fullscreen and non-fullscreen modes.

**Comment by EricHanLiu** [comment]
I can add the `f` key being used to toggle fullscreen. 

I'll see if I can also get the toolbar to display like it does in `Diva5`

**Comment by EricHanLiu** [comment]
Re-added the toolbar in fullscreen mode
