### ISSUE TITLE
New Plugin: IIIF Metadata Viewer

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#411]
There should be a new plugin to display the contents of the 'metadata' block on the IIIF manifest.

TODO: Determine the controls for how to show it.

**Comment by EricHanLiu** [comment]
Core of it is done, reviewable state at [metadata branch](https://github.com/DDMAL/diva.js/tree/metadata)

**Comment by EricHanLiu** [comment]
instead of opening in a new window, could have a modal pop up

**Comment by EricHanLiu** [comment]
Created pull request #417

**Comment by EricHanLiu** [comment]
Add ability to drag window and close with x button

**Comment by EricHanLiu** [comment]
New PR with draggable div and x button #419

**Comment by EricHanLiu** [comment]
Merged, closing
