### ISSUE TITLE
Testing: IIIFv2 and IIIFv3 support

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#412]
Make sure there are tests for both IIIFv2 and v3 manifests.

**Comment by EricHanLiu** [comment]
v3 image manifests aren't yet supported by the current manifest parser (from the IIIF AV Player). I thought the priority for that parser was to allow A/V compatibility, so there isn't currently a way to parse v3 manifests. 

This, coupled with the fact that we didn't have many examples of image manifests (I think we had one) made it a low-priority task at the time. Once the parser accepts v3 images **with Diva**, then some tests will be written.

**Comment by EricHanLiu** [comment]
Fixed by PR #430

**Comment by EricHanLiu** [comment]
Merged
