### ISSUE TITLE
Travis build fails when installing npm canvas

### ISSUE THREAD

**Issue by EricHanLiu** [DDMAL/diva.js#416]
Likely because `canvas` requires `cairo` as a backend which it doesn't install when building.

Here is the [latest failed build](https://travis-ci.org/DDMAL/diva.js/builds/408649792?utm_source=slack&utm_medium=notification).

@deepio

**Comment by deepio** [comment]
Have you tried installing `libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++` on the machine? 

`apt-get install -yq libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++ `
