### ISSUE TITLE
Handling no metadata in Metadata Plugin

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#425]
It is possible that a manifest will not have a metadata section. After #424 is merged, it will handle this silently by simply not showing the window when the plugin button is clicked.

What should happen is that the metadata icon will not appear in the toolbar when a manifest does not have a metadata section.

This may require some re-jigging of the internals, since it seems plugins are instantiated before the manifest is finished parsing. You may wish to defer the icon creation until after the `ManifestDidLoad` event. You can do this by registering a listener for this within the Metadata Plugin constructor, and then deferring the `createIcon` method call until then, when the manifest object is available for inspection.

**Comment by EricHanLiu** [comment]
Fixed by PR #429
