### ISSUE TITLE
Show labels instead of 'page numbers'

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#434]
Instead of `Page X of Y` we should show the IIIF canvas label of the current page when scrolling.

In opening mode we should show both labels, e.g., 

`f. 17v - f. 18r`

**Comment by EricHanLiu** [comment]
Fixed in latest commit, labels are shown instead of page numbers. in Book View, a label range is shown for the two pages.

**Comment by EricHanLiu** [comment]
See PR #435 for updates

**Comment by EricHanLiu** [comment]
# Add page labels to top right corner of each page

On top of having the toolbar label tool (for now)

**Comment by EricHanLiu** [comment]
All the bugs related to this issue have been fixed, closing.
