### ISSUE TITLE
Add reset to manipulation plugin

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#438]
Users should be able to reset the filters to defaults

**Comment by ahankinson** [comment]
That's not entirely obvious

**Comment by EricHanLiu** [comment]
Will add a reset button

**Comment by EricHanLiu** [comment]
Added in [commit](https://github.com/DDMAL/diva.js/commit/d262bdd6c4080fe09e73a3e744d8bf35626350c9)
