### ISSUE TITLE
Set diva-wrapper to take up full screen

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#441]
For the default viewer style, `diva-wrapper` should be set to `95vh` and the 700px height of `diva-outer` removed

https://github.com/DDMAL/diva.js/blob/develop/source/css/_viewer.scss#L5
https://github.com/DDMAL/diva.js/blob/develop/source/css/_viewer.scss#L232

**Comment by EricHanLiu** [comment]
Fixed in latest commit of `filter-queue` branch

**Comment by EricHanLiu** [comment]
This change causes the tests to fail. Looking at fixing

**Comment by EricHanLiu** [comment]
all my unit tests are failing now for some reason (only when doing a `single-run`, otherwise they pass in the debug runner). this is not exclusive to this branch.

what's going on?!

**Comment by EricHanLiu** [comment]
See issue #444

**Comment by EricHanLiu** [comment]
I'll leave these open until issue #444 is fixed and the tests work locally with these changes

**Comment by EricHanLiu** [comment]
Will push this aside since this breaks all the unit tests despite being a very small change.

**Comment by EricHanLiu** [comment]
I have a guess for why these fail when running in headless or chrome but not debug. I think the header that appears in Chrome also appears in HeadlessChrome and messes up the top scroll calculations (which are the tests that are failing), though i don't know for sure if that header appears in HeadlessChrome.

If this is the case then perhaps there's a way to remove it in the karma conf?

**Comment by EricHanLiu** [comment]
Created [an issue](https://github.com/karma-runner/karma/issues/3120) in the Karma repository

**Comment by EricHanLiu** [comment]
Fixed by adjust tests to work with 800x600 viewport since ChromeHeadless (Puppeteer) has these dimensions. 

For some reason, when the height was set at 700px and `min-height: 100%`, tests that should've perhaps broken with this viewport size were somehow passing. Maybe luck?
