### ISSUE TITLE
Zooming in on pages causes them to be cut off on the right

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#442]
When zooming in on a page on a fairly large screen there is an area on the right that masks the image.

It seems to be a problem with the size of the canvas not covering the full size of the viewport:

https://www.dropbox.com/s/9xrcg0qnef9q2gt/obscured-view.mov?dl=0

**Comment by EricHanLiu** [comment]
This was fixed by removing the maxExtent attribute in [commit](https://github.com/DDMAL/diva.js/commit/956d93f97fcfb8efaa69ac07ba0a4315b4e4aa7e)

**Comment by EricHanLiu** [comment]
I'll leave these open until issue #444 is fixed and the tests work locally with these changes

**Comment by EricHanLiu** [comment]
This can be closed because the latest failing commit doesn't affect this, it was fixed earlier.
