### ISSUE TITLE
Make threshold filter a different section

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#448]
The threshold filter isn't really combine-able with the other filters. It should be to be exclusive (either threshold OR others).

**Comment by EricHanLiu** [comment]
threshold filter is now in its own category (unique filters), and setting it resets the others (and vice versa)

**Comment by ahankinson** [comment]
I find the UI confusing. I'm not sure what a 'unique' filter is, or what the others are 'compatible' with.

How about a dropdown list with 'Color Adjustment' and 'Threshold'. Selecting the first (default?) brings up the color adjustments. Selecting the second brings up the thresholding adjustment. 

Then it's obvious that these controls are mutually exclusive.

**Comment by EricHanLiu** [comment]
ok

**Comment by EricHanLiu** [comment]
Fixed

**Comment by EricHanLiu** [comment]
@ahankinson it's next to the `Filters` title, there's a selection box for Color Filters or Threshold

**Comment by ahankinson** [comment]
<img width="268" alt="image" src="https://user-images.githubusercontent.com/163183/44734491-55999d80-aaea-11e8-97b8-d864595dac7d.png">

This is what I see?

**Comment by ahankinson** [comment]
(Also, what happened to the mirror button titles?)

**Comment by EricHanLiu** [comment]
Readded mirror buttons (think you removed them when resolving the conflict between branches)

Weird, i'll look into why you can't see the select
