### ISSUE TITLE
Implement saturation, gamma, color channel filters

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#449]
Saturation: https://github.com/meltingice/CamanJS/blob/master/src/lib/filters.coffee#L42-L58
Gamma: https://github.com/meltingice/CamanJS/blob/master/src/lib/filters.coffee#L210-L221

For the colour channel filter, implement r/g/b sliders individually.

Color Channel: https://github.com/meltingice/CamanJS/blob/master/src/lib/filters.coffee#L274-L305

**Comment by EricHanLiu** [comment]
Added these filters
