### ISSUE TITLE
Implement Rotate in manipulation plugin

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/diva.js#450]
Rotate and Zoom can be grouped together and available on all filters.

**Comment by EricHanLiu** [comment]
Added a WIP rotate tool. it rotates properly and is compatible with zoom / mirror / image filters, but doesn't properly adjust the size of the canvas so parts of the image get cut off.

I need a way to rotate the entire canvas element, not just something within the canvas (which is what's happening, the canvas element is still the same rectangle).

Using CSS transforms didn't work either, the top and left were still cut off, but the bottom worked more properly

**Comment by EricHanLiu** [comment]
Fixed!

**Comment by ahankinson** [comment]
The rotation should be live (move the slider, see the image rotate)

**Comment by EricHanLiu** [comment]
Done
