### ISSUE TITLE
ReferenceError: "Diva not defined"

### ISSUE THREAD

**Issue by martin-hinze** [DDMAL/diva.js#455]
Hello!
I am just trying to get started with Diva on our project server and it seems I am getting something basic wrong. I created the following little html page to start Diva:
```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Diva IIIF Viewer Test</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" href="/imageserver/build/diva/css/diva.css" />
  <script src="/imageserver/build/diva/js/diva.js" type="text/javascript"></script>
</head>

<body>
	<h1>Diva IIIF Viewer Test</h1>
	<div id="my-diva-box" style="width: 1000px; height: 1000px; border: 2px solid lightgray;"></div>
	<script>
		let diva = new Diva("my-diva-box", {
			objectData: "https://making-mysticism.org/imageserver/manifest-1.json"
		});
		console.log("Diva!");
	</script>
</body>
</html>
```
It is stored on our server [here](https://making-mysticism.org/imageserver/build/diva/example.html).
In the JS console I get the following error:
```
example.html:16 Uncaught ReferenceError: Diva is not defined
at example.html:16
```
Any ideas how to solve this would be very appreciated.
Best wishes,
Martin

**Comment by martin-hinze** [comment]
PS I also tried to do it as described in the wiki with
```
 <script>
    document.addEventListener('DOMContentLoaded', function ()
        {
            let diva = new Diva('diva-wrapper', {
                objectData: "https://making-mysticism.org/imageserver/manifest-1.json"
            });
        }, false)
    </script>
```
in the <head> -- same error: File stored [here](https://making-mysticism.org/imageserver/build/diva/example-2.html)

**Comment by ahankinson** [comment]
Hi Martin,

It seems as though you've caught us in the middle of updating the documentation for the new version of Diva that we're getting ready to release in the next few weeks. We have updated the documentation, but the release isn't quite ready.

If you want to use the upcoming release, you can checkout the code from the `develop` branch and use that. Then you will be able to use the documentation.

-Andrew

**Comment by EricHanLiu** [comment]
Hi Martin,

There is a version ready to use (but it is still under development), if you checkout the `develop` branch and run 
```bash
npm run build:production
```
then the build files (`diva.css, diva.js`, etc.) will appear under the `build/` directory and you can include those files in your `index.html`.

**Comment by EricHanLiu** [comment]
Closing this issue, to summarize:

Before diva 6 is officially released, in order to use it you'll need the source - clone and checkout the `develop` branch then follow the setup instructions, ie. run
```bash
npm install
npm run build:production
```
And then you can include the build files accordingly!

**Comment by martin-hinze** [comment]
Thank you so much, it worked. :-)
