### ISSUE TITLE
Does the method diva.getCurrentPageIndex exist?

### ISSUE THREAD

**Issue by martin-hinze** [DDMAL/diva.js#465]
Hello,

according to the [Wiki](https://github.com/DDMAL/diva.js/wiki/Public-Methods#getcurrentpageindex), there should be a method ```diva.getCurrentPageIndex```. Unfortunately, I am not able to call it. Shouldn't it work like this?
```var a = diva.getCurrentPageIndex();```
In the JS Console I just get an error:
```Uncaught TypeError: diva.getCurrentPageIndex is not a function at <anonymous>:1:6```
If this method existed, it would make things a lot easier for my project. :-)

Thank you and please keep up the good work.
Martin

**Comment by EricHanLiu** [comment]
Hi Martin,

Sorry about this, there was a small part of the wiki that hadn't yet been updated to the latest changes (released in v6). The actual method to use is
```javascript
var a = diva.getCurrentPageIndices();
```
which will return an array of the visible pages. You can alternatively use 
```javascript
var b = diva.getActivePageIndex();
```
which will function the way you probably want from `diva.getCurrentPageIndex();`. 

The wiki has been updated to accurately reflect the available methods. Thanks for bringing up this issue!
