### ISSUE TITLE
API request: hook for displaying property values

### ISSUE THREAD

**Issue by eroux** [DDMAL/diva.js#472]
Here is our use case:

We are dealing with languages that can be displayed in various manners, for instance:
- Tibetan displayed in:
   - Unicode Tibt script
   - EWTS transliteration
   - another transliteration usually used by scholars (which has no name)
- Sanskrit displayed in:
   - various Unicode scripts (Devanagari, Prachalit, and many others)
   - IAST transliteration
   - ISO15919 transliteration
   - (in some cases)Tibetan and the various Tibetan transliterations cited above

We allow our users to specify some preferences and want to display the labels of the manifests in the language and transliteration chosen by the user. We don't want to include all these labels into our manifests because moving from one transliteration to another is a 1:1 translation (and including them all would make our manifests less readable). So we would like to implement the mechanism to display a property value ourselves.

So the request is:

Would it be possible to allow users (in the sense of users of the API) to give Diva a JavaScript function taking the value of a Property Value and returning the string Diva should display? That way we would handle all the complexity ourselves.

(related: https://github.com/ProjectMirador/mirador/issues/1959 https://github.com/UniversalViewer/universalviewer/issues/646)

**Comment by ahankinson** [comment]
Hi @eroux -- The core of Diva is just a viewer; we're a bit different than mirador or UV in that we leave display of some things up to the implementer, including metadata.

That said, we do expose the `metadata` block from the IIIF manifest to the plugins:

https://github.com/DDMAL/diva.js/blob/master/source/js/plugins/metadata.js#L46

This is in our basic 'metadata' plugin, which will give you the ability to view the manifest metadata; see our "Metadata" plugin, and click on the 'tag' button in the toolbar.

http://ddmal.github.io/diva.js/try/metadata.html

**Comment by eroux** [comment]
ok
