### ISSUE TITLE
Template for new plugins

### ISSUE THREAD

**Issue by martin-hinze** [DDMAL/diva.js#473]
Hello! I need to write a few Diva toolbar plugins for the website of my project's digital book edition. I hope I am not asking too much, but it would be so great to have a sort of plugin template, where I can just insert my JS code and the SVG data of its icon. I tried to do this according to the ["Tutorial: Writing your own plugin"](https://github.com/DDMAL/diva.js/wiki/The-API-and-Plugins#tutorial-writing-your-own-plugin), yet as a JS beginner I would need some more assistance to reach this milestone. Also, when I looked at the code from the metadata plugin, I found some more functions than those described in the tutorial.
To begin with, I put the code from the tutorial together and ended up with this non functional code. For a beginning, it might be enough to just use a simple circle as placeholder. Any suggestions on how to create a working template from the snippets below would be highly appreciated.

```
constructor(core) {
    this.core = core;

    // toolbar tool
    this.toolbarIcon = this.createIcon();
    this.toolbarSide = 'right';
}

handleClick() {
    /* Plugin code goes here */
    window.alert("Click!");
}

createIcon() {
    const pageToolsIcon = document.createElement('div');
    pageToolsIcon.classList.add('diva-plugin icon');

    let root = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    root.setAttribute("x", "0px");
    root.setAttribute("y", "0px");
    root.setAttribute("viewBox", "0 0 25 25");
    root.id = `${this.core.settings.selector}plugin-icon`;

    let g = document.createElementNS("http://www.w3.org/2000/svg", "g");
    g.id = `${this.core.settings.selector}plugin-icon-glyph`;
    g.setAttribute("transform", "matrix(1, 0, 0, 1, -11.5, -11.5)");
    g.setAttribute("class", "diva-plugin-icon");

    let path = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path.setAttribute("d", "");

    g.appendChild(path);
    root.appendChild(g);

    pageToolsIcon.appendChild(root);

    return pageToolsIcon;
}

export default class NewDivaPlugin {
    // constructor
    // methods
}

MyPlugin.prototype.pluginName = "Describe plugin functionality";
MyPlugin.prototype.isPageTool = false;

/**
 * Make this plugin available in the global context
 * as part of the 'Diva' namespace.
 **/
(function(global) {
    global.Diva.NewDivaPlugin = NewDivaPlugin;
})(window);
```

**Comment by ahankinson** [comment]
Hi Martin! Have you had a look at this example plugin?

https://github.com/DDMAL/diva.js/blob/master/source/js/plugins/download.js

Don't forget that you also need to enable the plugin when you embed Diva on your page, like so:

https://github.com/DDMAL/diva.js/blob/master/index.html#L23

So I would expect that you would need to add `plugins: [Diva.NewDivaPlugin]` to the instantiation code for it to work.

**Comment by martin-hinze** [comment]
Dear Andrew,
thank you, this helps!
Best wishes,
Martin
