### ISSUE TITLE
Function gotoPageByIndex causes IndexSizeError in Firefox

### ISSUE THREAD

**Issue by martin-hinze** [DDMAL/diva.js#480]
While the method
```
diva.gotoPageByIndex()
```
is working beautifully in Google Chrome, it causes errors in Firefox. The image asked for is not displayed or rendering stops to early. Any suggestions how to fix this would be highly appreciated since most of our users use Firefox. :-)
I took a screenshot with a side by side comparison of Chrome and Firefox and the error messages.
![diva-error-000](https://user-images.githubusercontent.com/41114981/61363610-9b875d80-a884-11e9-888a-202ab5b4a728.jpg)

**Comment by ahankinson** [comment]
It's not the gotoPageByIndex method that's the problem, it's an issue with Firefox not being able to handle drawing the canvas. See: https://github.com/DDMAL/diva.js/issues/469

What version of Diva are you running? This issue should be fixed in 6.0.1.

**Comment by martin-hinze** [comment]
Thank you, problem is solved. I updated to version 6.0.1 from version 6.0.0.
Somehow
```
npm run build:production
```
did not work in the last days, but today it did. Thank you so much!
