### ISSUE TITLE
"Try it -> Default" does not render image

### ISSUE THREAD

**Issue by napulen** [DDMAL/diva.js#493]
Trying the [default ](https://ddmal.music.mcgill.ca/diva.js/try/single.html) *out-of-the-box* instance of Diva.js, as shown in the `Try it` section of the website.

However, the image does not load.

![image](https://user-images.githubusercontent.com/7258463/75113379-81cca680-561b-11ea-996d-7c4eb75a06f5.png)

The **Metadata Plugin** and **IIIF Integration** work as expected.

**Comment by JRegimbal** [comment]
Can you provide more information? The image loads as expected for me on Firefox 73.
![image](https://user-images.githubusercontent.com/6963142/75158835-f7e91000-56e4-11ea-9a58-02aa6798ea0b.png)

**Comment by napulen** [comment]
It is working now. I realized these images are being served through `images.simssa.ca`

Maybe ComputeCanada was having a rough day and that was it.

Thanks for checking. Closing it now.
