### ISSUE TITLE
Webpage won't load due to "Potential Security Risk Ahead"

### ISSUE THREAD

**Issue by emilyhopkins** [DDMAL/diva.js#517]
Not sure if it's the certificate or dependencies yet but wanted to mention right away
("Warning: Potential Security Risk Ahead")

**Comment by ahankinson** [comment]
The website is supposed to be https://ddmal.github.io/diva.js

When was it changed to https://diva.simssa.ca? The certificate doesn't match it, which is what is causing the problem.

**Comment by emilyhopkins** [comment]
Yes, @kemalkongar is updating the certificate, I forgot to update the issue here! Thanks!

**Comment by emilyhopkins** [comment]
Yes, the page is working again, thanks so much!

**Comment by napulen** [comment]
Reopening just to confirm whether @ahankinson is okay with the domain https://diva.simssa.ca/

I don't know when it changed exactly, I think it's been like that for a while. 

If not this one, another option would be https://ddmal.music.mcgill.ca/diva.js/

Any https://ddmal.github.io is automatically forwarded to https://ddmal.music.mcgill.ca, so we can't currently use github.io without affecting the custom domain of all DDMAL websites on github.

Nevertheless, currently, all previous urls should work and forward to https://diva.simssa.ca

- https://diva.simssa.ca
- https://ddmal.music.mcgill.ca/diva.js
- https://ddmal.github.io/diva.js

but let us know if you prefer to change it to something else

**Comment by ahankinson** [comment]
Is there a reason the address was changed?

I'm not sure what this means:

> Any https://ddmal.github.io is automatically forwarded to https://ddmal.music.mcgill.ca, so we can't currently use github.io without affecting the custom domain of all DDMAL websites on github.

I would expect that would mean that https://ddmal.github.io/diva.js wouldn't work, but that seems to still work as expected?

There should probably be a 301 redirect in place redirecting to a canonical URL, rather than having the same content on every page. Google doesn't really like the same content available on multiple URLs.

**Comment by napulen** [comment]
> Is there a reason the address was changed?

I don't know, we'd need to find out who changed it and when.

I am not sure if Amazon Route 53 has a log/history of changes, that'd be the easiest way to check.

> I'm not sure what this means:
> Any https://ddmal.github.io is automatically forwarded to https://ddmal.music.mcgill.ca, so we can't currently use github.io without affecting the custom domain of all DDMAL websites on github.

There is a custom domain set up for the github organization page, doing a GET request to ddmal.github.io does trigger a 301 to ddmal.music.mcgill.ca. 

![image](https://user-images.githubusercontent.com/7258463/142642775-1ccbc90a-aefb-45ff-9087-dfcc0039caf1.png)

There's another custom domain specifically set for the diva repo, doing a GET request to either ddmal.github.io/diva.js or ddmal.music.mcgill.ca/diva.js triggers a 301 to diva.simssa.ca. My impression is that any repo would abide by the custom domain of the organization, but whenever there is a custom domain for an individual repo, it overwrites the custom domain of the  organization, as in this case. For example: 
- ddmal.github.io/diva.js -> 301 -> diva.simssa.ca, and not
- ddmal.github.io/diva.js -> 301 -> ddmal.music.mcgill.ca/diva.js -> 301 -> diva.simssa.ca 

![image](https://user-images.githubusercontent.com/7258463/142643635-c50ebaca-fa4d-4289-8fa4-d762f92c4852.png)

**Comment by ahankinson** [comment]
I think this is fixed now.
