### ISSUE TITLE
Get the current page displayed

### ISSUE THREAD

**Issue by lguariento** [DDMAL/diva.js#519]
Hello,

I have started playing with diva again after a few years so please bear with me. I simply want to subscribe to the 'changing image' event. I want to get the file name of the currently visible image, like the implementation is seen on the top-right corner of the viewer. I'm using diva 6.0.2.

This is my current code:

```
    <script>
    document.addEventListener('DOMContentLoaded', function ()
        {
            let diva = new Diva('diva-wrapper', {
                objectData: "https://frontdoor.spa.gla.ac.uk/gdc/manifest/C/345809",
                plugins: [Diva.MetadataPlugin]
            });
        }, false)
        
        Diva.Events.subscribe('VisiblePageDidChange', function (filename, pageIndex)
{
    console.log('pageIndex: ' + pageIndex + ' and filename: '+ filename)
});
    </script>
```

One thing to note is that I have to use `Diva.Events`, and not `diva.Events` as stated in the Wiki, otherwise I get a 'diva is not defined' error. The output of the code above is `pageIndex: undefined and filename: 0,1`. Why undefined? What am I missing?

**Comment by ahankinson** [comment]
The manifest you gave has two canvases with the same `@id` value. I'm guessing it's not loading because it thinks the page hasn't changed.

Try with a different manifest?

**Comment by lguariento** [comment]
Thank you @ahankinson , I get the same thing with https://diva.simssa.ca/try/demo/iiifv3.json. Can you give me a manifest which is supposed to give the expected results so that I can test? Also, is that expected behaviour that I need to use `Diva` and not `diva`?

**Comment by ahankinson** [comment]
Yes, `Diva` is correct. Technically the two are aliases, but I guess only one is attached to the global window object.

Do you get any messages to your console? Did you try subscribing to any other messages to see if those work?

**Comment by lguariento** [comment]
My output is something like `pageIndex: undefined and filename: 0,1`, with the latest numbers changing: if it's displaying the first page it's `0`, if half of the first and half of the second `0,1`, etc, while filename is always undefined.

Would it be possible to get something from the manifest matadata (e.g. the folio number, which also changes)?

Also, shall I use `Diva` also for the [public methods](https://github.com/DDMAL/diva.js/wiki/Public-Methods)?

**Comment by ahankinson** [comment]
The public methods are attached to your instance variable. If you have, for example:

```
let charlieTheWonderDog = new Diva('diva-wrapper', {
                objectData: "https://frontdoor.spa.gla.ac.uk/gdc/manifest/C/345809",
                plugins: [Diva.MetadataPlugin]
            });
        }, false)
```

Then the public methods would start with `charlieTheWonderDog`. 

Did you try listening to another message? Did that work?

**Comment by ahankinson** [comment]
It looks like `VisiblePageDidChange` only publishes the indexes of the visible pages. See:

https://github.com/DDMAL/diva.js/blob/f977534acc0b0f67b6108059d006bead70494fb3/source/js/viewer-core.js#L1374

You can also try something like:

```
Diva.Events.subscribe('VisiblePageDidChange', function (pageIndex)
{
   let canvasUri = charlieTheWonderDog.getCurrentPageUri();
   console.log('pageIndex: ' + pageIndex + ' and canvas URI: '+ canvasUri)
});

**Comment by lguariento** [comment]
@ahankinson That's what I mean: using you code, with diva or Charlie or whatever :) , still gives me a `Uncaught ReferenceError: diva is not defined.` My whole bit of code:

```
document.addEventListener('DOMContentLoaded', function ()
        {
            let diva = new Diva('diva-wrapper', {
                objectData: "https://frontdoor.spa.gla.ac.uk/gdc/manifest/C/345809",
                plugins: [Diva.MetadataPlugin]
            });
        }, false)
        
Diva.Events.subscribe('VisiblePageDidChange', function (pageIndex)
{
   let canvasUri = diva.getCurrentPageUri();
   console.log('pageIndex: ' + pageIndex + ' and canvas URI: '+ canvasUri)
});
```

In the documentation I see _VisiblePageDidChange [pageIndex, filename]_. Am I wrong in thinking it should return the filename too then? Am I missing something?

**Comment by ahankinson** [comment]
You need to have the code inside of the `DOMContentLoaded` callback function, since that's the scope in which the variables are defined.

There were some changes to the API when we moved to IIIF; namely, that "filenames" don't make any sense, since they're all canvas URIs. It's not impossible that the documentation is out-of-sync with that.

**Comment by lguariento** [comment]
Thank you. New code:

```
    document.addEventListener('DOMContentLoaded', function ()
        {
            let diva = new Diva('diva-wrapper', {
                objectData: "https://frontdoor.spa.gla.ac.uk/gdc/manifest/C/345809",
                plugins: [Diva.MetadataPlugin]
            });
            let test = 'hello'
                        Diva.Events.subscribe('VisiblePageDidChange', function (pageIndex)
{
   console.log(test)
   let canvasUri = diva.getCurrentPageUri();
   console.log('pageIndex: ' + pageIndex + ' and canvas URI: '+ canvasUri)
});
        }, false)
```

I am getting 'hello'. I'm also getting `Uncaught TypeError: diva.getCurrentPageUri is not a function`. What am I doing wrong?

**Comment by lguariento** [comment]
OK, got it - it's `getCurrentPageURI`, I can now indeed get the current URI. Thanks!

**Comment by lguariento** [comment]
How can I get some more metadata like the folio, such as in [this example](https://diva.simssa.ca/try/metadata.html), where one can see `fol. ii v - fol. iv r` etc changing?

**Comment by ahankinson** [comment]
The best and most accurate way is to look through the public functions here:

https://github.com/DDMAL/diva.js/blob/master/source/js/diva.js#L650

https://github.com/DDMAL/diva.js/blob/f977534acc0b0f67b6108059d006bead70494fb3/source/js/toolbar.js#L122-L142

Remembering that there can be more than one visible page, the `getCurrentPageIndices()` will give you the page indexes of all the visible pages. Assuming you want the first and last, you select the first element in the incdices array, and the last one.

Then you look that those indices in the list of pages; you would replace `this.settings.manifest.pages[startIndex].l;` with `diva.settings.manifest.pages[startIndex].l;` (or whatever you called your instance variable). The `.l` property is the label on the pages.

The rest should be pretty easy to figure out -- only concat start/end labels, etc.

```            
            let indices = this.viewer.getCurrentPageIndices();
            let startIndex = indices[0];
            let endIndex = indices[indices.length - 1];
            let startLabel = this.settings.manifest.pages[startIndex].l;
            let endLabel = this.settings.manifest.pages[endIndex].l;

            if (startIndex !== endIndex)
            {
            	if (this.settings.enableIndexAsLabel)
                	currentPage.textContent = startIndex + " - " + endIndex;
            	else
            		currentPage.textContent = startLabel + " - " + endLabel;
            }
            else
        	{
            	if (this.settings.enableIndexAsLabel)
            		currentPage.textContent = startIndex;
            	else
            		currentPage.textContent = startLabel;
        	}
        };
```

**Comment by lguariento** [comment]
That's great, that `diva.settings.manifest.pages[startIndex].l` and the `.l` explanation is the key here for me. Thanks!
